In [1]:
import numpy as np

### Creating a single dimensional array

In [2]:
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

### Creating a multi-dimensional array

In [6]:
n2 = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
type(n2)

numpy.ndarray

### Initialize to all zeros

In [12]:
n1 = np.zeros((5,5))
print(n1, "\n")

n2 = np.zeros((1,2))
print(n2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0.]]


### Initialize to some value

In [14]:
n1 = np.full((3,3), 7)
n1

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### Initialize with range (here for odd numbers)

In [17]:
n1 = np.arange(1,10,2)
n1

array([1, 3, 5, 7, 9])

### Initialize with random numbers

In [22]:
n1 = np.random.randint(1,10,2)
print(n1, "\n")
 
n1 = np.random.randint(1,200,10)
print(n1)

[8 1] 

[  3  39   3  99 162  82 131 142   6  41]


### Finding the shape of the numpy array

In [26]:
n1 = np.full((3,3), 4)
print(n1)
n1.shape

[[4 4 4]
 [4 4 4]
 [4 4 4]]


(3, 3)

In [31]:
# This can be manipulated with the shape function

n1.shape = (3,3) #rows and columns

### Addition of numpy array

In [32]:
# Sum of all the elements 
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

np.sum([n1,n2])

21

In [35]:
# Sum of vertical axis (columns)
np.sum([n1, n2], axis=0)

array([5, 7, 9])

In [36]:
# Sum of horizontal axis (rows)
np.sum([n1,n2], axis=1)

array([ 6, 15])

### Joining numpy arrays with vstack(), hstack(), column_stack()

In [37]:
n1 = np.array([1,2,3])
n2 = np.array([8,9,10])

In [42]:
# vertical stack
np.vstack((n1,n2))

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [43]:
# horizontal stack
np.hstack((n1,n2))

array([ 1,  2,  3,  8,  9, 10])

In [44]:
# column stack
np.column_stack((n1,n2))

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10]])